### ISSUE TITLE
World stuck at 1% generation 

### ISSUE THREAD

**Issue by carrotee123** [chocolate-edition/Public-Issue-Board#12]
hey ive been waiting for 20 minutes for my world to generate and it didn't even move I checked my atlauncher logs and it says this

[17:29:05] [spark-java-sampler-0-1/WARN]: Timed out waiting for world statistics
[17:30:05] [spark-java-sampler-0-2/WARN]: Timed out waiting for world statistics
[17:31:05] [spark-java-sampler-0-5/WARN]: Timed out waiting for world statistics
[17:32:05] [spark-java-sampler-0-1/WARN]: Timed out waiting for world statistics
[17:33:05] [spark-java-sampler-0-1/WARN]: Timed out waiting for world statistics
[17:34:05] [spark-java-sampler-0-1/WARN]: Timed out waiting for world statistics
[17:35:05] [spark-java-sampler-0-3/WARN]: Timed out waiting for world statistics
[17:36:05] [spark-java-sampler-0-0/WARN]: Timed out waiting for world statistics
[17:37:05] [spark-java-sampler-0-4/WARN]: Timed out waiting for world statistics
[17:38:05] [spark-java-sampler-0-2/WARN]: Timed out waiting for world statistics
[17:39:05] [spark-java-sampler-0-3/WARN]: Timed out waiting for world statistics
[17:40:05] [spark-java-sampler-0-4/WARN]: Timed out waiting for world statistics
![Screenshot 2024-08-11 174003](https://github.com/user-attachments/assets/63c43ca6-ad14-44a4-9fa7-4bf203e1b8d9)

**Comment by GildedToxin** [comment]
Is this a new world? Or one you've already made?

**Comment by carrotee123** [comment]
> Is this a new world? Or one you've already made?

New Iwent to go make something to eat while I waited and it was still generating so I waited 20 more mins and it still showed 1% the background was changing so it wasn't frozen but it just didn't move past 1% no matter how long a waited

**Comment by GildedToxin** [comment]
im honestly not sure why it happened, it might be because you arent using the CF launcher? 

Personally Id recommend just making a new world, if it keeps happening can you post your latest log using [this website](https://mclo.gs/)? You can also msg in discord if youd rather do it there

**Comment by carrotee123** [comment]
> im honestly not sure why it happened, it might be because you arent using the CF launcher?
> 
> Personally Id recommend just making a new world, if it keeps happening can you post your latest log using [this website](https://mclo.gs/)? You can also msg in discord if youd rather do it there

no I don't like curse-forges launcher its filled with bloat and wayyyy to many ads going on in the background (my opinion) I will stick with ATlauncher and no thanks I don't like joining discords just cause I need to ask a question I'm already at max discord servers I can be in

**Comment by GildedToxin** [comment]
Very fair lol, give another world a shot and lmk how it goes!

**Comment by carrotee123** [comment]
> Very fair lol, give another world a shot and lmk how it goes!

Thank you I will try uninstalling and reinstalling the pack tomorrow

**Comment by carrotee123** [comment]
> Very fair lol, give another world a shot and lmk how it goes!

ok it worked now for some reason I reinstalled and this time didn't mess with my render distance made a world and it worked and I decided to see if that was the problem and no for some reason it generated successfully again I guess I just got really unlucky the first try generating a world and I was busy at the time so I didn't try generating again a second time but I guess rarely the world can just get stuck generating due to some kind of error

**Comment by GildedToxin** [comment]
Yay! Glad it's working! Enjoy the pack (:

**Comment by carrotee123** [comment]
> Yay! Glad it's working! Enjoy the pack (:

thanks though unfournatley today I might not be able to I'm very busy with real life stuff I guess if anyone finds this thread if the world is stuck just try again cause maybe I did just get some weird error
