### ISSUE TITLE
Game crashes when starting new world and world name has the number 8 in it

### ISSUE THREAD

**Issue by DaniellePashayan** [chocolate-edition/Public-Issue-Board#15]
When I go to create a world, I always make the world name the date that I'm starting it. I tried to make the world name "08142024", but when I press 8 on the numpad, the game crashes. Thought it was a fluke, so I tried again with the same result. I uninstalled the modpack and re-installed and got the same error. Installed directly from CurseForge.

Error Code:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null

Log File: https://mclo.gs/mlmfTwD

**Comment by GildedToxin** [comment]
It's a known issue with one of the default keybinds, should be fixed in 1.7 

Are you playing on the most recent version?
