### ISSUE TITLE
Picking Up Bee Crashes Players

### ISSUE THREAD

**Issue by Devano101** [chocolate-edition/Public-Issue-Board#2]
Picking up bees, only LGBees as far as I know. I do not remember what variant of LGBee, but I'm assuming it's all LGBees. Was encountered in a four-player survival world, but was clearly replicated, started, and stopped multiple times and the cause of the player-based crash was consistent. Did not crash server however, so it was likely a rendering error of sorts.

Steps to Reproduce:

1. Use most recent version of Chocolate Edition (1.5.3.2)
2. Pick up LGBee using the Shift+Right Click method

Observed Results:
Crashes all players within render distance. As the render crash is attached to the player (or rather the picked-up entity is attached to the player), subsequent crashes upon player rejoining will occur. A /kill of the bee may be possible if it still counts as an entity in the picked-up state, otherwise there is sometimes enough time upon rejoining the server to put down the bee, which stops the line of crashing.

Error Logs Included:
N/A. None obtained from result, if unable to replicate, please ping @.datacat and I will perform the crash again and obtain logs.

**Comment by Jonah-Hansen** [comment]
fixed a while ago by blacklisting bees from carryon
