### ISSUE TITLE
"Loot Chest" Deleted Items :(

### ISSUE THREAD

**Issue by Jesswim29** [chocolate-edition/Public-Issue-Board#20]
In my world, I live in a village house that had a **naturally spawned "Loot Chest,"** which looks like a normal vanilla chest. I believe the bug lies within it being unsearchable/uncraftable, but after I had completely filled it over the course of several dozens of days of mob grinding, I intended to destroy it because it **would not extend with a new "Chest" for a double chest,** just stayed separated. But, when I destroyed it, only a "Chest" dropped, and my face went pale lol, as I don't have cheats active. So yeah, **when "Loot Chest" is broken, all items inside disappear...**

**Comment by Jonah-Hansen** [comment]
this is a known thing due to lootr. 

we have a warning on our discord regarding it but haven't gotten around to putting it in the quest book yet.
