### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by kreap1** [chocolate-edition/Public-Issue-Board#24]
![image](https://github.com/user-attachments/assets/585a22fa-edfc-415c-9a4f-c4838ddf2377)
I'm having horrible stutters and lower fps than I should be getting, but the weird thing is that when I'm in any menu(pause, inventory, quest screen, chests, etc) my fps doubles or even triples and starts running at my normal fps I should be getting, but not when im playing moving/looking around. Also worth mentioning this is on multilayer so the ticks aren't freezing. it seems to maybe be some kind of cpu related issue because if I turn shaders off and on there's is no difference at all in my fps. Im running on rx6600 with ryzen53400g, Ive never struggled running any modpacks before (for comparison I can run bettermc and atm9 with shaders at 200+fps)

**Comment by iakfar** [comment]
is vsync on? have had that happen sometimes

**Comment by kreap1** [comment]
> is vsync on? have had that happen sometimes

No its not, It doesn't seem to have any impact 
I've messed around a lot with my settings and nothing seems to fix it really

**Comment by kreap1** [comment]
An update, I found out what is causing the lag is the minimap, more specifically most of it is coming from the FTB claims overlay. Having the overlay on for the map for some reason caused unstable chunk loading and fps. This also explains why my framerate is back to normal while paused and in inventory

**Comment by iakfar** [comment]
certified journeymap moment

**Comment by MrFlamazing** [comment]
It is laggy and buggy without the minimap also. Does not want to render chunks and crash on me twice after freezing and not responding button came up. I like the modpack, just the performance is terrible right now.

**Comment by iakfar** [comment]
prob make your own issue, don't really want to spam this one with more tech support. can post f3 menu/spark report in there
spark command is /spark profiler start --thread * --timeout 50

**Comment by MrFlamazing** [comment]
Sorry
