### ISSUE TITLE
Crystallized Coral for Exotic Eye is unobtainable from Coralssus'

### ISSUE THREAD

**Issue by RadNotRed** [chocolate-edition/Public-Issue-Board#7]
Hello, in an update to the Cataclysm mod, the Coralssus no longer drops the crystallized coral, and from my experience, the mob that does drop it does not spawn naturally. I looked for multiple hours for the Coral Golem to no avail, which is the mob that actually drops the crystallized coral as of now. 

![image](https://github.com/user-attachments/assets/161c8cfe-9dd6-4ffc-801a-ad7e5eb13c88)

I looked in the Cataclysm city and coral reefs for the Coral Golem, and the Cataclysm docs don't really mention it other than ["In a recent Cataclysm update, the Coralssus was reworked, and the original Coralssus was turned into the Coral Golem." ](https://www.minecraft-guides.com/wiki/cataclysm/coralssus/)

**Comment by Jonah-Hansen** [comment]
this is fixed in 1.6.2, making coral chunks craft into crystalized coral
